<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Tesseract.UnitTests" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\Leptonica\Leptonica.csproj" />
      <ProjectReference Include="..\Tesseract.Contracts\Tesseract.Contracts.csproj" />
    </ItemGroup>
</Project>
